name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Java 환경 설정
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Maven 빌드 및 테스트
      - name: Build with Maven
        run: mvn clean package

      # 4. SSH 설정
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts

      # 5. EC2로 배포
      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          set -e

          # 애플리케이션 디렉토리 이동 또는 생성
          if [ -d "/home/ec2-user/app" ]; then
            cd /home/ec2-user/app
            git reset --hard
            git pull origin main
          else
            git clone https://github.com/greenlotte4/lotte-2nd-project-back-team3.git /home/ec2-user/app
            cd /home/ec2-user/app
          fi

          # Maven 빌드 및 실행
          mvn clean package -DskipTests
          pkill -f 'java' || true
          nohup java -jar target/*.jar > /home/ec2-user/app/app.log 2>&1 &
          EOF
